version: 2.0
subscriptionId: b9d2281e-dcd5-4dfd-9a97-0d50377cdf76
resourceGroup: mcr
registry: k8svolume
onboardingNotification: k8sdev
dependencyNotification: k8sdev


repos:

  - name: public/k8s/flexvolume/blobfuse-flexvolume
    displayName: K8s Flexvolume Blobfuse Flexvolume
    readme: README.blobfuse-flexvolume.md
    description: Blobfuse flexvolume allows Kubernetes to access virtual filesystem backed by Azure Blob storage
    logoUrl: https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg
    supportLink: https://microsoft.com
    documentationLink: https://microsoft.com

  - name: public/k8s/flexvolume/smb-flexvolume
    displayName: K8s Flexvolume Smb Flexvolume
    readme: README.smb-flexvolume.md
    description: This driver allows Kubernetes to access SMB server by using CIFS/SMB protocol.
    logoUrl: https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg
    supportLink: https://microsoft.com
    documentationLink: https://microsoft.com

  - name: public/k8s/csi/azuredisk-csi
    displayName: K8s Azure Disk CSI Driver
    readme: README.azuredisk-csi.md
    description: This driver allows Kubernetes to use azure disk volume.
    logoUrl: https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg
    supportLink: https://microsoft.com
    documentationLink: https://microsoft.com
    syndications:
      - type: cloud
        destinations:
          - usnat
          - ussec
        tags:
          - source: v1.1.1
          - source: v0.9.0
          - source: /^v\d\.\d{1,2}\.\d{1,2}$/

  - name: public/k8s/csi/azurefile-csi
    displayName: K8s Azure File CSI Driver
    readme: README.azurefile-csi.md
    description: This driver allows Kubernetes to use azure file volume.
    logoUrl: https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg
    supportLink: https://microsoft.com
    documentationLink: https://microsoft.com
    syndications:
      - type: cloud
        destinations:
          - usnat
          - ussec
        tags:
          - source: v1.0.0
          - source: /^v\d\.\d{1,2}\.\d{1,2}$/


  - name: public/k8s/csi/blobfuse-csi
    displayName: K8s Blobfuse CSI Driver
    readme: README.blobfuse-csi.md
    description: This driver allows Kubernetes to use blob storage volume.
    logoUrl: https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg
    supportLink: https://microsoft.com
    documentationLink: https://microsoft.com

  - name: public/k8s/csi/smb-csi
    displayName: K8s SMB CSI Driver
    readme: README.smb-csi.md
    description: This driver allows Kubernetes to access SMB server by using CIFS/SMB protocol.
    logoUrl: https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg
    supportLink: https://microsoft.com
    documentationLink: https://microsoft.com

  - name: public/k8s/csi/nfs-csi
    displayName: K8s NFS CSI Driver
    readme: README.nfs-csi.md
    description: This driver allows Kubernetes to access NFS server by using NFS protocol.
    logoUrl: https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg
    supportLink: https://microsoft.com
    documentationLink: https://microsoft.com
    
  - name: public/k8s/local-volume-provisioner
    displayName: K8s Local Volume Provisioner
    readme: README.local-volume-provisioner.md
    description: This driver enable Kubernetes workloads using local disks.
    logoUrl: https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg
    supportLink: https://microsoft.com
    documentationLink: https://microsoft.com

  - name: public/k8s/csi/blob-csi
    displayName: Azure Blob Storage CSI driver
    readme: README.blob-csi.md
    description: Azure Blob Storage CSI driver for Kubernetes.
    logoUrl: https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg
    supportLink: https://microsoft.com
    documentationLink: https://microsoft.com
